name: C++ CI

on: [push]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: download catch2
      run: wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -P catch2/
    - name: make test
      run: make test
    - name: run tests
      run: ./bin/tests
