name: C++ CI

on: [push]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make test
      run: make test
    - name: run tests
      run: ./bin/tests
